[build]
# Use Python 3.11
builder = "NIXPACKS"

[deploy]
# Start command for FastAPI
startCommand = "python api_server.py"

# Health check endpoint
healthcheckPath = "/"
healthcheckTimeout = 300

# Restart policy
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
# Environment variables will be set in Railway dashboard
# RAILWAY_ENVIRONMENT will be automatically set by Railway 